// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GoToFileOnLine
{
    internal sealed partial class Vsix
    {
        public const string Id = "GoToFileOnLine.2027e58d-53a3-4dce-8e55-bf02942c94d6";
        public const string Name = "GoToFileOnLine";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Daniel Sandberg";
        public const string Tags = "";
    }
}
