// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GoToFileOnLine
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string GoToFileOnLineString = "61417d77-683e-4efb-b9e9-b16f8128f4cd";
        public static Guid GoToFileOnLine = new Guid(GoToFileOnLineString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GoToFileOnLineGroup = 0x0001;
        public const int GoToFileOnLineCommand = 0x0100;
    }
}
