// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GoToFileOnLine
{
    internal sealed partial class Vsix
    {
        public const string Id = "2027e58d-53a3-4dce-8e55-bf02942c94d6";
        public const string Name = "Go to File on Line";
        public const string Description = @"A combination of Go To File and Go To Line. Search for a file and add :LINENUMBER to open the file and select the line.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "BDSoftware";
        public const string Tags = "";
    }
}
